src/src/Entity/Annonce.php
<?php

namespace App\Entity;

use App\Repository\AnnonceRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AnnonceRepository::class)]
class Annonce
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column]
    private ?int $price = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $Date = null;

    #[ORM\ManyToOne(inversedBy:'annonces',targetEntity:User::class)]
    private ?User $IdUser = null;

    #[ORM\ManyToOne(inversedBy: 'IdAnnonce')]
    private ?Tag $tag = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getIdUser(): ?User
    {
        return $this->IdUser;
    }

    public function setIdUser(?User $IdUser): self
    {
        $this->IdUser = $IdUser;

        return $this;
    }

    public function getTag(): ?Tag
    {
        return $this->tag;
    }

    public function setTag(?Tag $tag): self
    {
        $this->tag = $tag;

        return $this;
    }

    public function hydrate(array $donnees)
    {
        foreach($donnees as $cle =>$valeur) {
            $method='set'.ucfirst($cle);
            if(method_exists($this,$method)) {
                return $this->$method($valeur);
            }
        }
    }

 
}

src/src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $LastName = null;

    #[ORM\Column(length: 255)]
    private ?string $FirstName = null;

    #[ORM\Column]
    private ?bool $isSeller = null;

    #[ORM\OneToMany(mappedBy: 'idUserVote', targetEntity: Vote::class, fetch: 'EAGER')]
    private Collection $votes;

    public function __construct()
    {
        $this->votes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastName(): ?string
    {
        return $this->LastName;
    }

    public function setLastName(string $LastName): self
    {
        $this->LastName = $LastName;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->FirstName;
    }

    public function setFirstName(string $FirstName): self
    {
        $this->FirstName = $FirstName;

        return $this;
    }

    public function isIsSeller(): ?bool
    {
        return $this->isSeller;
    }

    public function setIsSeller(bool $isSeller): self
    {
        $this->isSeller = $isSeller;

        return $this;
    }

    public function getVoteScore(): int
    {
        return count($this->getVotes());
    }

    /**
     * @return Collection<int, Vote>
     */
    public function getVotes(): Collection
    {
        return $this->votes;
    }
}

src/templates/site/add_annonce.html.twig
{% extends 'base.html.twig' %}

{% block title %} ADD ANNOUNCE {% endblock %}



{% block body %}
<div class="m-4 w-full">
    <p class="text-xl mb-6 text-black"> Ajouter une annonce</p>
    {{ form(form) }}
</div>

{% endblock %}

src/templates/site/add_answer.html.twig
{% extends 'base.html.twig' %}

{% block title %} ADD Answer {% endblock %}



{% block body %}

<h1 class="font-bold text-2xl text-neutral-800 mb-4">Répondre à une question</h1>

{{ form(form) }}

{% endblock %}

src/templates/site/add_question.html.twig
{% extends 'base.html.twig' %}

{% block title %} ADD QUESTION {% endblock %}



{% block body %}

<h1 class="font-bold text-2xl text-neutral-800 mb-4">Poser une question</h1>

{{ form(form) }}

{% endblock %}

src/templates/site/edit_annonce.html.twig
{% extends 'base.html.twig' %}

{% block title %} Update ANNOUNCE {% endblock %}



{% block body %}
{{ form_start(annonceForm) }}
    {{ form_row(annonceForm.title, {
        label: 'Article title'
    }) }}
    {{ form_row(annonceForm.price) }}
    {{ form_row(annonceForm.description) }}
    {{ form_row(annonceForm.date) }}
    <button type="submit" class="btn btn-primary">Update!</button>
{{ form_end(annonceForm) }}

{% endblock %}

src/templates/site/edit_pass.html.twig
{% extends 'base.html.twig' %}

{% block title %} profil {% endblock %}



{% block body %}

<section class="bg-gray-50 dark:bg-gray-900">
  <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
      
      <div class="w-full p-6 bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md dark:bg-gray-800 dark:border-gray-700 sm:p-8">
          <h2 class="mb-1 text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
              Modifier le mot de passe
          </h2>

      
          <form class="mt-4 space-y-4 lg:mt-5 md:space-y-5"  method="POST">
            
              <div>
                  <label for="password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Nouveau mot de passe</label>
                  <input type="password" name="password" id="password" placeholder="••••••••" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required="">
              </div>
              <div>
                  <label for="confirm-password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Confirmation du nouveau mot de passe </label>
                  <input type="password" name="password2" id="password2" placeholder="••••••••" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required="">
              </div>
              <button type="submit" class="w-full text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">Réinitialiser le mot de passe</button>
          </form>
      </div>
  </div>
</section>


{% endblock %}

src/templates/site/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} Leboncoin {% endblock %}

{% block body %}
<h1 class="text-3xl font-bold text-neutral-800">Annonces</h1>
<div class="z-990 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-3 gap-3 w-full py-10">
{% for annonce in annonces %}
<div class="p-6 bg-white shadow-md light:bg-gray-800">
    <a href="#">
        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-blue">
		{{ annonce.title }}</h5>
        <div>
            <span class="text-sm text-gray-500 dark:text-gray-400">
            by <span class="font-bold">{{ annonce.getIdUser().getFirstName }}</span>
            the <span class="font-bold">{{ annonce.getDate()|date('d-m-Y') }}</span>
            </span>

                {% if (is_granted('IS_AUTHENTICATED_REMEMBERED')) %}
                    <a href="{{ path('app_vote_action', {id: annonce.id}) }}" class="inline-flex items-center py-1 px-2 ml-16 text-sm font-medium text-center text-white bg-gray-700 rounded-lg hover:bg-gray-800 focus:ring-4 focus:outline-none focus:ring-gray-300 dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-gray-800">
                        <svg width="1em" height="1em" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 text-white-500 white:text-white-400">
                            <path d="M9.456 4.216l-5.985 7.851c-.456.637-.583 1.402-.371 2.108l.052.155a2.384 2.384 0 002.916 1.443l2.876-.864.578 4.042a2.384 2.384 0 002.36 2.047h.234l.161-.006a2.384 2.384 0 002.2-2.041l.576-4.042 2.877.864a2.384 2.384 0 002.625-3.668L14.63 4.33a3.268 3.268 0 00-5.174-.115zm3.57.613c.16.114.298.253.411.411l5.897 7.736a.884.884 0 01-.973 1.36l-3.563-1.069a.884.884 0 00-1.129.722l-.678 4.75a.884.884 0 01-.875.759h-.234a.884.884 0 01-.875-.76l-.679-4.75a.884.884 0 00-1.128-.72l-3.563 1.068a.884.884 0 01-.973-1.36L10.56 5.24a1.767 1.767 0 012.465-.41z" fill="currentcolor" fill-rule="evenodd">
                            </path>
                        </svg>
                    </a>
                {% else %}
                    <a class="inline-flex items-center py-1 px-2 ml-16 text-sm font-medium text-center text-white bg-gray-700 rounded-lg opacity-50 cursor-not-allowed">
                        <svg width="1em" height="1em" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 text-white-500 white:text-white-400">
                            <path d="M9.456 4.216l-5.985 7.851c-.456.637-.583 1.402-.371 2.108l.052.155a2.384 2.384 0 002.916 1.443l2.876-.864.578 4.042a2.384 2.384 0 002.36 2.047h.234l.161-.006a2.384 2.384 0 002.2-2.041l.576-4.042 2.877.864a2.384 2.384 0 002.625-3.668L14.63 4.33a3.268 3.268 0 00-5.174-.115zm3.57.613c.16.114.298.253.411.411l5.897 7.736a.884.884 0 01-.973 1.36l-3.563-1.069a.884.884 0 00-1.129.722l-.678 4.75a.884.884 0 01-.875.759h-.234a.884.884 0 01-.875-.76l-.679-4.75a.884.884 0 00-1.128-.72l-3.563 1.068a.884.884 0 01-.973-1.36L10.56 5.24a1.767 1.767 0 012.465-.41z" fill="currentcolor" fill-rule="evenodd">
                            </path>
                        </svg>
                    </a>
                {% endif %}

                <span class="text-sm text-gray-500 dark:text-gray-400">
                    {{ annonce.getIdUser().getVoteScore() }}
                </span>
        </div>
    </a>
    <p class="mb-3 font-normal text-gray-700 dark:text-gray-500">
	{{ annonce.description }}</p>
	<span
        class="flex flex-wrap justify-between items-center text-xs sm:text-xs bg-gray-200 light:bg-gray-800 dark:hover:bg-gray-300 rounded px-4 py-2 leading-loose cursor-pointer dark:text-gray-500 w-fit mb-5">
        {{ annonce.getTag().getTag() }}
    </span>
    <div class="flex justify-between items-end">
        <a href="{{ path('app_annonce_show', {'id':annonce.id}) }}" class="inline-flex items-center py-2 px-3 text-sm font-medium text-center text-white rounded-md focus:outline-none bg-gray-700 hover:bg-gray-900 ">En savoir plus
            <svg aria-hidden="true" class="ml-2 -mr-1 w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
        </a>
        <p class="font-bold text-xl">{{ annonce.price }} €</p>
    </div>
</div>
{% endfor %}



</div>
{% endblock %}

src/templates/site/profil.html.twig
{% extends 'base.html.twig' %}

{% block title %} profil {% endblock %}



{% block body %}

<section class="bg-blueGray-50">
<div class="w-full  px-4 mx-auto">
  <div class="relative flex flex-col min-w-0 break-words bg-white w-full mb-6 shadow-xl rounded-lg ">
    <div class="px-6">
      <div class="flex flex-wrap justify-center">
        <div class="w-full px-4 flex justify-center">
          <div class="relative">
            <img alt="..." src="{{ asset('img/avatar.png') }}" class="shadow-xl rounded-full h-auto align-middle border-none absolute -m-16 -ml-20 lg:-ml-16 max-w-150-px">
          </div>
        </div>
        <div class="w-full px-4 text-center mt-20">
          <div class="flex justify-center py-4 lg:pt-4 pt-8">
            <div class="mr-4 p-3 text-center">
              <span class="text-xl font-bold block uppercase tracking-wide text-blueGray-600">
                  {{app.user.annonces|length}}
              </span>
              <span class="text-sm text-blueGray-400">Annonces</span>
            </div>
            <div class="mr-4 p-3 text-center">
              <span class="text-xl font-bold block uppercase tracking-wide text-blueGray-600">
                10
              </span>
              <span class="text-sm text-blueGray-400">Likes</span>
            </div>
            <div class="lg:mr-4 p-3 text-center">
              <span class="text-xl font-bold block uppercase tracking-wide text-blueGray-600">
                89
              </span>
              <span class="text-sm text-blueGray-400">Comments</span>
            </div>
          </div>
        </div>
      </div>
      <div class="text-center mt-12">
        <h3 class="text-xl font-semibold leading-normal mb-2 text-blueGray-700 mb-2">
          {{app.user.lastName}} {{app.user.firstName}}
        </h3>
        <div class="text-sm leading-normal mt-0 mb-2 text-blueGray-400 font-bold uppercase">
          <i class="fas fa-envelope mr-2 text-lg text-blueGray-400"></i>
          {{app.user.email}}
        </div>
         <div class="text-sm leading-normal mt-0 mb-2 text-blueGray-400 font-bold uppercase">
          <a href="{{ path('app_edit_pass')}}" class="inline-flex items-center py-2 px-3 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mr-3">
  <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L6.832 19.82a4.5 4.5 0 01-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 011.13-1.897L16.863 4.487zm0 0L19.5 7.125" />
</svg>
                
                Modifier le mot de passe

          </a>
        </div>
      </div>
      <div class="mt-10  border-t border-blueGray-200 text-center">
          <div class="z-990 grid grid-cols-1 sm:grid-cols-1 lg:grid-cols-é xl:grid-cols-2 gap-6 w-full" style="max-width: 900px;margin: 80px auto;">
        {% for annonce in app.user.annonces %}
        <div class="p-6 max-w-sm bg-white rounded-lg border border-gray-200 shadow-md light:bg-gray-800">
            <a href="#">
                <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-blue">
            {{ annonce.title }}</h5>
            <span class="text-sm text-gray-500 dark:text-gray-500">
            posté le <span class="font-bold">{{ annonce.getDate()|date('d-m-Y') }}</span>
            </span>
            </a>
            <p class="mb-3 font-normal text-gray-700 dark:text-gray-500">
          {{ annonce.description }}</p>
          <span
                class="flex flex-wrap justify-between items-center text-xs sm:text-xs bg-gray-200 light:bg-gray-800 dark:hover:bg-gray-300 rounded px-4 py-2 leading-loose cursor-pointer dark:text-gray-500 w-fit mb-5">
                {{ annonce.getTag().getTag() }}
            </span>
            <a href="{{ path('app_annonce_show', {'id':annonce.id}) }}" class="inline-flex items-center py-2 px-3 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                {{ annonce.price }} €
                <svg aria-hidden="true" class="ml-2 -mr-1 w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
            </a>
        </div>
        {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>

</section>


<footer class="relative  pt-8 pb-6 mt-8">
 
</footer>
{% endblock %}

src/templates/site/search_annonce.html.twig
{% extends 'base.html.twig' %}

{% block title %} Leboncoin - Rechercher une annonce {% endblock %}



{% block body %}
<div class="container">
    <div class="">
        <div class="col-md-3">
            {% include 'annonce/_filter.html.twig' with {form : form} only %} 
        </div> 
        <div class="col-md-9"> 
            <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-3 gap-3 w-full py-10">
                {% for annonce in annonces %} 
                    {% include 'annonce/_card.html.twig' with {annonce : annonce} only %} 
                {% endfor %} 
            </div>
            {% if annonces|length <= 0 %} 
                <p>pas d'offre trouvre</p>
            {% endif %} 
        </div>
    </div>
</div>
{% endblock %}

src/templates/site/see_annonce.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ annonce.title }} {% endblock %}



{% block body %}
<div class="p-6 bg-white shadow mb-6">
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-2 gap-3 w-full">
        {% for image in images %}
            <img class="w-full lg:max-h-96 md:max-h-60 sm:max-h-24 max-h-96 object-cover object-center mb-10" src={{asset('/uploads/' ~ image)}}>
        {% endfor %}
    </div>
    <h1 class="mb-2 text-3xl font-bold tracking-tight text-neutral-900 capitalize">
    {{ annonce.title }}</h1>
    <span
        class="flex flex-wrap justify-between items-center text-xs sm:text-sm leading-loose cursor-pointer text-neutral-500 font-medium mb-2 w-fit">
        {{ annonce.getTag().getTag() }}
    </span>
    <span class="text-sm text-gray-500 dark:text-gray-400">
    by <span class="font-bold">{{ annonce.getIdUser().getFirstName }}</span>
    the <span class="font-bold">{{ annonce.getDate()|date('d-m-Y') }}</span>
    </span>
    
    <p class="mb-6 font-normal text-gray-500 dark:text-gray-40 text-md">{{ annonce.description }}</p>
    {% if(annonce.getIdUser().getId() == userId) %}
        <div class="mb-8">
            <a href="{{ path('app_annonce_delete', {'id':annonce.id}) }}" ><button type="button" class="focus:outline-none text-neutral-500 hover:text-neutral-700 bg-gray-200 hover:bg-gray-300 font-medium rounded-md text-sm px-5 py-2.5 mb-2 mr-4">Delete</button></a>
            <a href="{{ path('app_annonce_update', {'id':annonce.id}) }}" ><button type="button" class="focus:outline-none text-white bg-gray-700 hover:bg-gray-900 font-medium rounded-md text-sm px-5 py-2.5 mb-2">Update</button></a>
        </div>
    {% endif %}

    <div >
        <h2 class="font-bold text-xl mb-6 text-neutral-800">Questions posées par les utilisateurs</h2>
            {% for question in questions %}
                <div class="p-6 bg-neutral-100 shadow mb-4">
                    <p class="text-sm mb-2">{{ question.getIdUser().getFirstName() }}</p>
                    <div class="flex">
                        <p class="mr-2 font-medium">Question :</p>
                        <p>{{ question.question }}</p>
                    </div>
                    {% if(annonce.getIdUser().getId() == userId) %}
                        {% if not(question.getIdAnswer() is null) %}
                            <div class="flex">
                                <p class="mr-2 font-medium">Réponse du vendeur :</p>
                                <p>{{ question.getIdAnswer().getAnswer() }}</p>
                            </div>
                        {% else %}
                            <a href="{{ path('app_add_answer', {'id':question.id}) }}" ><button type="button" class="focus:outline-none text-white bg-gray-700 hover:bg-gray-900 font-medium rounded-md text-sm px-5 py-2.5 mt-2">Répondre</button></a>
                        {% endif %}
                    {% else %}
                        {% if not(question.getIdAnswer() is null) %}
                            <div class="flex">
                                <p class="mr-2 font-medium">Réponse du vendeur :</p>
                                <p>{{ question.getIdAnswer().getAnswer() }}</p>
                            </div>
                        {% endif %}
                    {% endif %}
                </div>
            {% endfor %}
            {% if not(annonce.getIdUser().getId() == userId or userId == null) %}
                <div class="flex justify-center">
                    <a href="{{ path('app_add_question', {'id':annonce.id}) }}" ><button type="button" class="focus:outline-none text-white bg-gray-700 hover:bg-gray-900 font-medium rounded-md text-sm px-5 py-2.5 mt-8">Poser une question</button></a>
                </div>
            {% endif %}
    </div>
</div>



{% endblock %}